[package]
name = "gateway-service"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { version = "1", features = ["full"] }
warp = "0.3.2"

consul_oxide = { git = "https://github.com/kaylendog/consul-oxide" }

proto = { path = "../proto" }
